version: '3.7'

services:
  database:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env

    volumes:
      - database:/var/lib/mysql
      - ./create-database.sql:/create-database.sql
    ports:
      - 3307:3306
volumes:
  database:
